### ISSUE TITLE
请问这个添加之后的连接符是什么呢

### ISSUE THREAD

**Issue by wannayi** [sheenli/autoChangeXode#1]
![image](https://user-images.githubusercontent.com/34264399/68856690-1faafe00-071c-11ea-9f55-67fc0d84c6e9.png)

**Comment by sheenli** [comment]
啥意思？

**Comment by wannayi** [comment]
![{7E5CCEC0-9733-A78B-93F8-2B6459F076EF}](https://user-images.githubusercontent.com/34264399/68857033-e0c97800-071c-11ea-859e-0722fdee4a73.png)
这个要添加的是什么呢

**Comment by sheenli** [comment]
一般比如 -Objc这样的
